arm2_scooping_grasp:
  ros__parameters:
    robot_ip: "192.168.1.201"
    get_scooping_point_service: "food_perception/get_scooping_point"
    trigger_service_name: "arm2/execute_grasp"
    selected_bowl_idx: -1
    auto_execute_on_index_set: true
    target_frame: "xarm2_base"

    tf_timeout_sec: 1.0
    service_timeout_sec: 5.0
    request_retries: 2

    use_apriltag_target: true
    fallback_to_bowl_centroid: false
    apriltag_target_id: 0
    bowl_idx_to_tag_id: [-1, 1, 0]
    tag_frame_templates: ["tag36h11:{id}"]
    # tag_to_gripper_xyz: [0.077028, -0.170170, -0.857843]
    # tag_to_gripper_rpy: [1.512064, 0.078675, 0.083398]
    tag_to_gripper_xyz: [0.0, 0.0, 0.0]
    tag_to_gripper_rpy: [0.0, 0.0, 0.0]
    apriltag_request_retries: 1
    apriltag_pose_max_age_sec: 0.8
    use_apriltag_orientation: false

    default_speed: 60.0
    default_accel: 120.0
    motion_type: 0

    use_current_orientation: true
    target_orientation_rpy: [0.0, -1.571, 3.141]

    point_offset_xyz: [0.0, 0.0, 0.0]
    approach_z_offset: 0.08
    grasp_z_offset: 0.0
    lift_z_offset: 0.12

    gripper_open_pos: 850.0
    gripper_close_pos: 120.0
    gripper_speed: 2000.0

    use_workspace_limits: false
    workspace_min_xyz: [200.0, -400.0, 80.0]
    workspace_max_xyz: [700.0, 400.0, 500.0]
