arm_control_node:
  ros__parameters:
    # Robot Parameters
    robot_type: "lite6"
    robot_ip: "192.168.1.190"
    default_speed: 80  # mm/s
    default_accel: 50   # mm/s^2

    # Robot Poses
    poses:
      perception_pose: [79.2, 128.1, 471.7, 2.691, -0.1693, 2.646]
      transfer_pose: [-69.4, 238.3, 225.6, 2.187, -0.723, 2.950]
      reset_pose: [-39.8, 182.9, 222.9, 1.899, -0.808, 3.098]
      
    # Bite Transfer Parameters
    bite_threshold: 3.0  # N
    spoon_length: 0.270  # m
